export const COMPLETE_ONBOARDING = "COMPLETE_ONBOARDING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const INVALID_LOGIN = "INVALID_LOGIN";
export const LOADING = "LOADING";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const LOGIN_NETWORK_ERROR = "LOGIN_NETWORK_ERROR";
export const LOGOUT = "LOGOUT";
export const POPULATE_FILES = "POPULATE_FILES";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const POPULATE_USERS = "POPULATE_USERS";
export const POPULATE_CHATS = "POPULATE_CHATS";
export const POPULATE_MESSAGES = "POPULATE_MESSAGES";
export const STORE_FILES = "STORE_FILE";
export const REGISTER_EXISTED = "REGISTER_EXISTED";
export const DELETE_CHATS = "DELETE_CHATS";
export const ADD_PEOPLE_TO_CHAT="ADD_PEOPLE_TO_CHAT"
export const POPULATE_MESSAGES_BY_ID = "POPULATE_MESSAGES_BY_ID";
export const DELETE_PEOPLE_FROM_CHAT="DELETE_PEOPLE_FROM_CHAT"

// export const ADD_NEW_CHATS = "ADD_NEW_CHATS"

